In [ ]:
import pandas as pd
import numpy as np

In [ ]:
num_rows = 50
data = {
    "produto": [f"produto{i}" for i in range(1, num_rows +1)],
 "categoria": np.random.choice (["tv", "celular", "tablet", "impressora", "computador"], size=num_rows),
 "preco": np.random.uniform(100.0,200.0, size=num_rows).round(2),
 "quantidade_no_estoque": np.random.randint(1,50, size=num_rows)
}
df = pd.DataFrame(data)

In [ ]:
df

      produto   categoria   preco  quantidade_no_estoque
0    produto1     celular  119.14                     41
1    produto2  computador  145.09                     12
2    produto3      tablet  130.98                     49
3    produto4          tv  109.46                      9
4    produto5  computador  183.11                     20
5    produto6     celular  190.78                     37
6    produto7  computador  163.42                     11
7    produto8     celular  160.54                     11
8    produto9      tablet  110.36                     30
9   produto10          tv  128.30                     10
10  produto11     celular  117.89                     38
11  produto12  computador  198.34                     46
12  produto13  impressora  148.15                     49
13  produto14  impressora  133.39                     20
14  produto15     celular  141.33                     38
15  produto16          tv  122.53                     25
16  produto17      tablet  132.86                     34
17  produto18      tablet  106.25                      2
18  produto19          tv  171.98                     25
19  produto20     celular  107.47                     11
20  produto21      tablet  155.87                     15
21  produto22  computador  148.90                     24
22  produto23          tv  161.98                     15
23  produto24     celular  162.01                     33
24  produto25      tablet  196.33                      7
25  produto26  impressora  178.20                     47
26  produto27      tablet  141.09                     22
27  produto28  computador  192.04                     23
28  produto29  computador  102.72                     14
29  produto30          tv  118.45                     26
30  produto31          tv  135.88                     11
31  produto32     celular  127.46                     40
32  produto33     celular  172.28                     46
33  produto34          tv  124.51                     22
34  produto35      tablet  191.46                     13
35  produto36     celular  127.21                     28
36  produto37          tv  174.20                     48
37  produto38          tv  144.68                     14
38  produto39  computador  136.95                      9
39  produto40          tv  192.87                      9
40  produto41     celular  145.68                      7
41  produto42      tablet  190.83                     10
42  produto43      tablet  115.88                     13
43  produto44  computador  105.60                      4
44  produto45     celular  140.83                      2
45  produto46     celular  180.75                     39
46  produto47  computador  158.48                     40
47  produto48  computador  117.95                     21
48  produto49     celular  109.23                     39
49  produto50  computador  155.78                     11

In [ ]:
df ['receita'] = df["preco"]* df["quantidade_no_estoque"]

In [ ]:
df

      produto   categoria   preco  quantidade_no_estoque  receita
0    produto1     celular  119.14                     41  4884.74
1    produto2  computador  145.09                     12  1741.08
2    produto3      tablet  130.98                     49  6418.02
3    produto4          tv  109.46                      9   985.14
4    produto5  computador  183.11                     20  3662.20
5    produto6     celular  190.78                     37  7058.86
6    produto7  computador  163.42                     11  1797.62
7    produto8     celular  160.54                     11  1765.94
8    produto9      tablet  110.36                     30  3310.80
9   produto10          tv  128.30                     10  1283.00
10  produto11     celular  117.89                     38  4479.82
11  produto12  computador  198.34                     46  9123.64
12  produto13  impressora  148.15                     49  7259.35
13  produto14  impressora  133.39                     20  2667.80
14  produto15     celular  141.33                     38  5370.54
15  produto16          tv  122.53                     25  3063.25
16  produto17      tablet  132.86                     34  4517.24
17  produto18      tablet  106.25                      2   212.50
18  produto19          tv  171.98                     25  4299.50
19  produto20     celular  107.47                     11  1182.17
20  produto21      tablet  155.87                     15  2338.05
21  produto22  computador  148.90                     24  3573.60
22  produto23          tv  161.98                     15  2429.70
23  produto24     celular  162.01                     33  5346.33
24  produto25      tablet  196.33                      7  1374.31
25  produto26  impressora  178.20                     47  8375.40
26  produto27      tablet  141.09                     22  3103.98
27  produto28  computador  192.04                     23  4416.92
28  produto29  computador  102.72                     14  1438.08
29  produto30          tv  118.45                     26  3079.70
30  produto31          tv  135.88                     11  1494.68
31  produto32     celular  127.46                     40  5098.40
32  produto33     celular  172.28                     46  7924.88
33  produto34          tv  124.51                     22  2739.22
34  produto35      tablet  191.46                     13  2488.98
35  produto36     celular  127.21                     28  3561.88
36  produto37          tv  174.20                     48  8361.60
37  produto38          tv  144.68                     14  2025.52
38  produto39  computador  136.95                      9  1232.55
39  produto40          tv  192.87                      9  1735.83
40  produto41     celular  145.68                      7  1019.76
41  produto42      tablet  190.83                     10  1908.30
42  produto43      tablet  115.88                     13  1506.44
43  produto44  computador  105.60                      4   422.40
44  produto45     celular  140.83                      2   281.66
45  produto46     celular  180.75                     39  7049.25
46  produto47  computador  158.48                     40  6339.20
47  produto48  computador  117.95                     21  2476.95
48  produto49     celular  109.23                     39  4259.97
49  produto50  computador  155.78                     11  1713.58

In [ ]:
df["preco_ao_quadrado"] = df.apply

In [ ]:
df["preco"].min()

np.float64(102.72)

In [ ]:
df["preco"].mean()

np.float64(146.5494)

In [ ]:
df["preco"].std()

np.float64(28.627805622064255)

In [ ]:
df["preco"].max()

np.float64(198.34)

In [ ]:
df_filtrando = (df["categoria"] == "computador")

In [ ]:
df_filtrando2 = df[df["preco"] >500] & (df["categoria"] == "computador")

In [ ]:
df_filtrando3 = df[df["preco"] >400] & (df["categoria"] =="impressora")

In [ ]:
caminho = R"C:\Users\kleberson_belem\Downloads\nomeatt.xlsx"

In [ ]:
df.to_excel(caminho, engine= "openpyxl")

In [ ]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

In [1]:
caminho_arquivo = r'C:\Users\kleberson_belem\Downloads\Frutas.xlsx'
df_frutas = pd.read_excel(caminho_arquivo)

NameError: name 'pd' is not defined

In [ ]:
df_frutas

     Fruta     Cor        Gosto      Formato    Casca
0     Limão     Verde      Azedo      Oval       Liso
1   Limão     Amarelo    Azedo      Oval       Peludo
2     Limão     Verde      Doce       Oval       Liso
3     Limão     Amarelo    Azedo      Oval       Liso
4   Limão     Verde      Doce       Oval       Peludo
5     Banana    Amarelo    Doce       Curvado    Liso
6     Banana    Amarelo    Doce       Curvado    Liso
7   Banana    Amarelo    Doce       Curvado    Peludo
8   Banana    Amarelo    Azedo      Curvado    Peludo
9   Banana    Amarelo    Doce       Curvado    Peludo
10    Abacaxi   Amarelo    Doce       Alongado   Liso
11    Abacaxi   Marrom     Doce       Alongado   Liso
12  Abacaxi   Amarelo    Azedo      Alongado   Peludo
13  Abacaxi   Amarelo    Azedo      Alongado   Peludo
14  Abacaxi   Amarelo    Doce       Alongado   Peludo
15    Abacaxi   Amarelo    Doce       Alongado   Liso
16  Abacaxi   Amarelo    Doce       Alongado   Peludo
17    Abacaxi   Amarelo    Doce       Alongado   Liso
18    Abacaxi   Marrom     Doce       Alongado   Liso
19    Abacaxi   Amarelo    Doce       Alongado   Liso
20    Kiwi      Marrom     Azedo      Oval       Liso
21  Kiwi      Verde      Doce       Oval       Peludo
22    Kiwi      Marrom     Doce       Oval       Liso
23    Kiwi      Verde      Azedo      Oval       Liso
24    Kiwi      Marrom     Doce       Oval       Liso
25    Kiwi      Marrom     Azedo      Oval       Liso
26  Kiwi      Marrom     Doce       Oval       Peludo
27  Kiwi      Marrom     Azedo      Oval       Peludo
28    Kiwi      Verde      Azedo      Oval       Liso
29  Kiwi      Verde      Doce       Oval       Peludo
30  Kiwi      Verde      Azedo      Oval       Peludo
31    Kiwi      Marrom     Azedo      Oval       Liso
32  Kiwi      Verde      Azedo      Oval       Peludo
33    Kiwi      Marrom     Azedo      Oval       Liso
34    Kiwi      Marrom     Azedo      Oval       Liso

In [ ]:
df_frutas = df_frutas['Fruta     Cor        Gosto      Formato    Casca'].str.split(expand=True)

df_frutas.columns = ['Fruta', 'Cor', 'Sabor', 'Formato','Textura']

NameError: name 'df_frutas' is not defined

In [ ]:
X = df_frutas[['Cor','Sabor','Formato', 'Textura']]
 
Y = df_frutas['Fruta']

In [ ]:


mapeamento_cor = {'Verde': 0, "Amarelo":1, 'Marrom':2}
mapeamento_sabor = {'Azedo':0, 'Doce':1}
mapeamento_formato = {"Oval":0, 'Curvado':1, 'Alongado':2}
mapeamento_textura = {'Liso':0,'Peludo':1}

In [ ]:
X = df_frutas[['Cor', 'Sabor', 'Formato', 'Textura']]

X['Cor'] = X['Cor'].map(mapeamento_cor)
X['Sabor'] = X['Sabor'].map(mapeamento_sabor)
X['Formato'] = X['Formato'].map(mapeamento_formato)
X['Textura'] = X['Textura'].map(mapeamento_textura)

C:\Users\kleberson_belem\AppData\Local\Temp\ipykernel_10992\3530158828.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Cor'] = X['Cor'].map(mapeamento_cor)
C:\Users\kleberson_belem\AppData\Local\Temp\ipykernel_10992\3530158828.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Sabor'] = X['Sabor'].map(mapeamento_sabor)
C:\Users\kleberson_belem\AppData\Local\Temp\ipykernel_10992\3530158828.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Formato'] = X['Formato'].map(mapeamento_formato)
C:\Users\kleberson_belem\AppData\Local\Temp\ipykernel_10992\3530158828.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Textura'] = X['Textura'].map(mapeamento_textura)

In [ ]:
X

    Cor  Sabor  Formato  Textura
0     0      0        0        0
1     1      0        0        1
2     0      1        0        0
3     1      0        0        0
4     0      1        0        1
5     1      1        1        0
6     1      1        1        0
7     1      1        1        1
8     1      0        1        1
9     1      1        1        1
10    1      1        2        0
11    2      1        2        0
12    1      0        2        1
13    1      0        2        1
14    1      1        2        1
15    1      1        2        0
16    1      1        2        1
17    1      1        2        0
18    2      1        2        0
19    1      1        2        0
20    2      0        0        0
21    0      1        0        1
22    2      1        0        0
23    0      0        0        0
24    2      1        0        0
25    2      0        0        0
26    2      1        0        1
27    2      0        0        1
28    0      0        0        0
29    0      1        0        1
30    0      0        0        1
31    2      0        0        0
32    0      0        0        1
33    2      0        0        0
34    2      0        0        0

In [ ]:
X['Textura'] = X["Textura"].map(mapeamento_textura)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=37)
modelo = DecisionTreeClassifier()
modelo.fit(X_train, y_train)
previsoes = modelo.predict(X_test)

C:\Users\kleberson_belem\AppData\Local\Temp\ipykernel_10992\489353455.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Textura'] = X["Textura"].map(mapeamento_textura)

In [ ]:
caminho_arquivo2 = r'C:\Users\kleberson_belem\Downloads\Frutas2.xlsx'
df_frutas2 = pd.read_excel(caminho_arquivo2)

df_frutas2['Cor'] = df_frutas2['Cor'].map(mapeamento_cor)
df_frutas2['Sabor'] = df_frutas2['Sabor'].map(mapeamento_sabor)
df_frutas2['Formato'] = df_frutas2['Formato'].map(mapeamento_formato)
df_frutas2['Textura'] = df_frutas2['Textura'].map(mapeamento_textura)
previsoes_novo_dados = modelo.predict(df_frutas2)

In [ ]:
previsoes_novo_dados

array(['Banana', 'Kiwi', 'Banana', 'Abacaxi', 'Kiwi'], dtype=object)